### ISSUE TITLE
Projects Not Showing

### ISSUE THREAD

**Issue by CSPutera** [moongift/TodoistGanttChartView#1]
Hello, I filled the auth key but projects were not loaded, I checked on Firebug but it shows no err. Please help, thank you.

**Comment by moongift** [comment]
@CSPutera 

Todoist change their security policy. So there is no jsonp callback, and we cannot access to API from Web browser.

https://todoist.com/Support/show/70106/

I'll change system soon, wait it.

**Comment by CSPutera** [comment]
Alright, looking forward for the update. Thank you very much.

**Comment by spartyguy** [comment]
"Failed to load resource: The requested URL was not found on this server: file:///TodoistGanttChartView-master/js/jquery-1.10.2.min.map" is not loading, any help would be appreciated. This looks great

**Comment by spainbox** [comment]
perhaps you can consider to import backup files to create gantt charts
regards

**Comment by ygordev** [comment]
Are we going to get an update on this?

**Comment by moongift** [comment]
@CSPutera 
@spartyguy 
@spainbox 
@ygordev 

Sorry, you wait long time. I updated this project, so you can use it again.

Best regards.

**Comment by moongift** [comment]
I got an another problem. I asked to Todoist support. Wait a time.

**Comment by spainbox** [comment]
@moongift  after i enter the Auth token and nothing happend.

<img width="1440" alt="screen shot 2016-06-29 at 05 59 25" src="https://cloud.githubusercontent.com/assets/17703064/16449724/ab4d380e-3dbe-11e6-9a6d-52098b23c109.png">

**Comment by spartyguy** [comment]
When entering the auth code, I get the choice of all my projects 👍 

The only problem is none of the information displays with the bars as it should. So, the Todoist functionality is there, but not the results...

**Comment by moongift** [comment]
@spartyguy 
@spainbox 

Sorry. I made a misstake how to use an API. I got a support from Todoist developer team.

Finally I fix a bug, so you can get a gantt chart right now.

https://todoistgantt.herokuapp.com
